### ISSUE TITLE
Words which are links are not highlighted

### ISSUE THREAD

**Issue by dryh2o** [fastaddons/AutoHighlight#1]
When creating a rule that is intended to highlight a word that is also a link, the word is not highlighted.

Open the website https://www.reddit.com/
Create a rule to highlight the word "hide"
The word "hide" is not highlighted despite it appearing in the site multiple times

Linux Mint 20
Firefox 83.0.3 64 Bit
AutoHighlight 2.3

**Comment by fastaddons** [comment]
Hello,
Could you send me more specific steps to reproduce? So that I can follow the steps and it will 100% fail.
I've tried it now and it seems to work fine.
Also make sure the rule is active on reddit domain and that you don't have "case sensitive" active.

But yeah, reddit is a special site (they mutate content a lot) and I had issues with it before, but now it should be more-less fine.
