### ISSUE TITLE
Text Box Size

### ISSUE THREAD

**Issue by o-data** [fastaddons/AutoHighlight#20]
**Is your feature request related to a problem? Please describe.**
I use a big RegularExpress list and it getting a bit too long, now have to scroll left and right.

**Describe the solution you'd like**
Can you set the text box size to be large or make it multiple lines?

**Describe alternatives you've considered**
Maybe it can auto expand as the box text increased.

**Additional context**
How I highlight is a long list multi words quote so after about 100 character is getting difficult to keep track.

**Comment by fastaddons** [comment]
Done, next version 4.7 will have an auto-growing text area, that should make things much better for long texts.
I'll try to release it this week.

**Comment by o-data** [comment]
[https://github.com/fastaddons/AutoHighlight/issues/20#issuecomment-1410547669](https://github.com/fastaddons/AutoHighlight/issues/20#issuecomment-1410547669)

Thank you!

---

Off topic: I notice that your Github is relatively hidden, is it intentional that it wasn't added to your website/homepage?

**Comment by fastaddons** [comment]
Not intentional :), my homepage was created first - a loooong time ago when there was no Github page for support.
I do put github link into each addon page (usually in "About" section).

My homepage needs a big redesign so I'm not investing a lot of time into it.
But good point, I think I'll add it there. Thank you for the pointing it out!
