### ISSUE TITLE
Website loads very slowly

### ISSUE THREAD

**Issue by Fritz1976** [fastaddons/AutoHighlight#9]
Hello
I have a lot of markings within a domain and because of that the respective page loads very slowly.
Would it be possible to load the page fully first and add the markings afterwards.
Or do you know a better solution so that the page no longer freezes when loading, because there will still be some markings.
I would be very grateful for a solution.

**Comment by fastaddons** [comment]
Hello,
Just to verify, this is not related to the recent update 2.8 from yesterday, right?

Also, it would be nice if you could share exact steps to reproduce the problem - including the page and the highlight rule.
There can be multiple performance issues - for example avoid RegExp if possible because that can be really slow.
Also, "after page loads" often means different things since many pages loads additional data after they are initially loaded, so it's hard to tell what would help.

But I'm open to optimization to improve performance.

**Comment by Fritz1976** [comment]
This has nothing to do with the last update.
With the highlighting rules is only activated via element
Firefox shows above then again and again Auto Highliter slows down the Firefox I keep the extension on loads the page immediately.

**Comment by fastaddons** [comment]
> With the highlighting rules is only activated via element
What do you mean?
So no RegExp?

And how many matches is on the page - see the toolbar icon which should have a badge number saying how many matches there is.

**Comment by Fritz1976** [comment]
No RegEx
Markings on page 61

**Comment by fastaddons** [comment]
Hmmm.... that doesn't sound right. It should be able to handle thousand of matches with no issues.

Let's try an experiment, after the page is loaded and everything is working fine, open the popup and click the "On / Off" toggle in the right corner (or use "Ctrl + Alt + H" shortcut) - that will toggle between adding and removing all highlights. Tell me, how fast is it? Are the highlights created right away or how long does it take?

**Comment by Fritz1976** [comment]
Hello
I tried that once, when I turn it off I have to first scroll the page so that the markings disappear.
When switched ON, Firefox again shows the Auto Highlighter slowing down the browser, I would say about 10 to 15 seconds.

**Comment by fastaddons** [comment]
That's bad :(
This means that even if I delay the initial marking after everything is loaded, it wouldn't help much.
Also, I can't optimize the highlight code because it's handled by the [Mark.js](https://markjs.io/) library I'm using.

But I could add option to skip initial marking when static html page is loaded and wait for the whole page to loaded. Because if I see it right, currently there are two markings happening right now for each page.

**Comment by Fritz1976** [comment]
So from programming I have zero idea, but if it solves the problem, I'm for it.

**Comment by fastaddons** [comment]
New version 3.0 was just released and in the Settings / General, you can now enable "Delay initial highlight on page load to improve performance".
This should improve initial load time because it won't do the re-highlight (which is kind of redundant, but may be required in some cases...).

Anyway, if the highlighting itself is slow, then this will help only partially. And since the highlighting is handled by a 3rd party library, I can't improve that.

**Comment by Fritz1976** [comment]
The new setting has no effect

**Comment by fastaddons** [comment]
Let me just quickly release 3.1 :), there is a race condition and the option may not be loaded when page is loaded.
But still, don't have high hopes.

**Comment by fastaddons** [comment]
3.1 has just been released for Firefox and now the option will be correctly applied. I'm sorry for the confusion :)

**Comment by Fritz1976** [comment]
It's a pity that it doesn't work properly, the extension has to be deactivated. It's a pity, on the whole, it was a good extension

**Comment by fastaddons** [comment]
So 3.1 hotfix didn't helped? :(
I'm sorry I couldn't help more.

**Comment by fastaddons** [comment]
Hello again,
Just to let you know, the new version 4.4 may help with performance, see the new option once you get the update:
https://github.com/fastaddons/AutoHighlight/issues/13#issuecomment-1200128633
